/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://a6i3qls735gx3jbkm5yxzxri2u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gkn6m7cojvhnhnwp6p7slha7xe",
    "aws_cognito_identity_pool_id": "us-east-1:cf260407-d6d7-4499-bfaf-dd30e8ab6319",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nzHoqknYb",
    "aws_user_pools_web_client_id": "5je3uabbv4fnhjajikdha8do6n",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "GIVEN_NAME",
        "FAMILY_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "userauth-storage-country-flags-290844-sampledev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
